services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: restoqr_root_2024
      MYSQL_DATABASE: restoqr_api_production
      MYSQL_USER: restoqr_api
      MYSQL_PASSWORD: restoqr_db_pass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./Rails
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_MASTER_KEY: "1918d11d41f6d8ac75969e8457c56895"
      DATABASE_URL: "mysql2://restoqr_api:restoqr_db_pass@db:3306/restoqr_api_production"
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "1"
      SOLID_QUEUE_IN_PUMA: "true"

volumes:
  mysql_data:
